'use strict'
const bcrypt = require('bcrypt')
module.exports = {
    async up(queryInterface, Sequelize) {
        return queryInterface.bulkInsert('Users', [
            {
                user_id: 'a224e56e-69dd-4608-b873-588e629ec6d4',
                user_no: '2019-00001-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'adf95bf0-9e28-4752-8fe1-d86e8593a544',
                user_no: '2019-00002-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'f7b9b71a-490c-412b-bfd0-055aabe0a5b2',
                user_no: '2019-00003-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'b9dd0a57-efed-4c37-934c-e38e4be5924d',
                user_no: '2019-00004-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '6b06a683-3493-4a2d-8f54-e14c49dc0d89',
                user_no: '2019-00005-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'a62db0f5-24ce-4930-86f4-9e197618011a',
                user_no: '2019-00006-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '385a592f-b5fe-43a8-82b1-43d2486f56f4',
                user_no: '2019-00007-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '7fb4e3a8-02fa-44a5-8fb1-e2aea59c890a',
                user_no: '2019-00008-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '6afde99f-38c9-4ff0-a3d8-69569a151e97',
                user_no: '2019-00009-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'de811aec-a5be-4fbd-a3c5-931c7caf5c42',
                user_no: '2019-00010-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '64226e3c-7f57-401e-a8ec-cae00b5f67ca',
                user_no: '2019-00011-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'd8439ad2-6498-42b9-b863-27bf894050ab',
                user_no: '2019-00012-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'becd05e5-0a73-4501-91b2-32cec89c875f',
                user_no: '2019-00013-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '933263ea-0497-41ec-9b99-339973e5f1fa',
                user_no: '2019-00014-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '3992c71e-12bf-4610-bab8-160f7ca98fcd',
                user_no: '2019-00015-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'cc3cac83-9d8b-4f0e-b955-0722627e27c7',
                user_no: '2019-00016-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'b6450096-4449-4a3b-b1d3-6979033b1417',
                user_no: '2019-00017-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'de443d73-b259-49dd-a31d-32b8be956845',
                user_no: '2019-00018-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '4c5695eb-5da8-4a3c-9bb6-b5bdf1e0f3a0',
                user_no: '2019-00019-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '2385f036-a124-4a0f-9a82-a1534d162523',
                user_no: '2019-00020-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '5ff40851-b385-442b-bdc6-a3277173c2be',
                user_no: '2019-00021-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '78a80843-21e5-47db-96bd-e621c0c00cd1',
                user_no: '2019-00022-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'c8c59be2-ad39-4eb2-83aa-3f8bc0e67cd5',
                user_no: '2019-00023-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'c10a0a2c-bab3-4ddf-8d41-cc7db97ecb5a',
                user_no: '2019-00024-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '316ccb50-f19d-407e-a09a-41c7fe3faf06',
                user_no: '2019-00025-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '786fee96-0460-4d90-ad47-998bd625f04f',
                user_no: '2019-00026-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '83daaa36-d3a7-47f0-8dfe-3bd4f38f2d14',
                user_no: '2019-00027-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '5e443a8c-b27e-4e42-909a-9e35631a0221',
                user_no: '2019-00028-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '62cdf0b4-dd30-480a-ae85-a6a6c257c2b4',
                user_no: '2019-00029-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'dfdecd9e-c18b-4979-a1d2-a803d03fbdf5',
                user_no: '2019-00030-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'cae022ad-cad7-4d62-953c-00b0bb990e26',
                user_no: '2019-00031-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'bad2efa6-d881-489e-bdf3-321869fd6975',
                user_no: '2019-00032-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'ff4d7153-b378-44a1-be68-b16cdbcba785',
                user_no: '2019-00033-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '48d7de08-8ac1-40a4-a5f3-0a146d527400',
                user_no: '2019-00034-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '40d7dd69-632d-4482-944a-73da25e0780a',
                user_no: '2019-00035-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '2e3b7adc-e396-44cd-beba-5232249ae4e4',
                user_no: '2019-00036-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'f2f0b1f5-e97f-452b-9018-9aa0d8607e93',
                user_no: '2019-00037-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '40dc12bb-cd93-4742-81f2-8067c3b1e785',
                user_no: '2019-00038-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '60fab159-2b74-4bc5-b6b8-5ecda0c3e7ce',
                user_no: '2019-00039-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'eff28db1-f2f9-4ca2-9c71-a66e3f02f21b',
                user_no: '2019-00040-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '6b9ea03e-58d5-4094-ba71-9766e51d1515',
                user_no: '2019-00041-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'aec00de5-42ba-455a-8900-1bfb9df13ecb',
                user_no: '2019-00042-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'cfbab520-1b86-4343-96c7-23283228b8ae',
                user_no: '2019-00043-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '9cd03861-664d-4bef-b1c5-2ed7c09c9d59',
                user_no: '2019-00044-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '45a20938-c3a5-4612-9994-422eda8e11c7',
                user_no: '2019-00045-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '1014185a-8718-40d5-875d-2ea0995f09d1',
                user_no: '2019-00046-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '0229d6d6-6eb7-4c41-b236-1ec50ae011c5',
                user_no: '2019-00047-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '0c0ea07c-ded1-4c43-8df3-acc3dd4afec7',
                user_no: '2019-00048-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: 'ae38a52a-84cf-4432-9598-605c98be663a',
                user_no: '2019-00049-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '667cf4f4-23c6-43cf-8cd9-e32f8a6a879e',
                user_no: '2019-00050-CM-0',
                user_type: 'Student',
                password: bcrypt.hashSync('student@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '176925fb-605b-4ceb-b0e8-edf178a96d9f',
                user_no: 'staff1@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '6310e7fb-8d23-4100-8304-ed68fc72531b',
                user_no: 'staff2@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '1c9beef4-7513-4ba3-a5ff-e558016dc935',
                user_no: 'staff3@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '4020a801-5195-47aa-9d50-7e90e519455b',
                user_no: 'staff4@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '9547e14c-55f1-4b5c-b0de-aa60fa0567f3',
                user_no: 'staff5@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
            {
                user_id: '8b5e036e-72ff-4159-8ec6-af1b06e2de9a',
                user_no: 'staff6@pup.edu.ph',
                user_type: 'PUP Staff',
                password: bcrypt.hashSync('staff@123', parseInt(process.env.SALT_ROUND)),
                created_at: new Date(),
                updated_at: new Date(),
            },
        ])
    },

    async down(queryInterface, Sequelize) {},
}
